# Module 4: Built int Database Functions 


## Built-in Functions 

- Most databases come with built-in SQL functions 
- Built-in functions can be included as part of SQL statements 
- Database functions can significantly reduce the amount of data that need to be retrieved 
- Can speed up data processing 

## Aggregate or Column functions 

- INPUT: Collection of values (e.g. entire column)
- Output: Single value
- Examples: SUM(), MIN(), MAX(), AVG(), etc.

## SUM

SUM function; Add up all the values in a column.
``` SUM(COLUMN_NAME)```

Example: Add all values in the COST column:
```select SUM(COST) from PETRESCUE```

By default, the result column it given a number as a name.

## Column Alias

Example: Explicitly name the output column SUM_OF_COST:

``` select SUM(COST) as SUM_OF_COST from PETRESCUE ```


## MIN, MAX

MIN: return the MINIMUM value
MAX: Return the MAXIMUM value

Example: Get the maximum QUANTITY of any ANIMAL:

``` select MAX(QUANTITY) from PETRESCUE ```

Example: Get the minium value of ID column for Dogs:

``` select MIN(ID) from PETRESCUE where ANIMAL = 'dog' ```

## Average

AVG() return the average value 

Example: Specify the Average value of COST:

``` select AVG(COST) from PETRESCUE ```

Mathematical operations can be performed between columns.

Example: Calculate the average COST per 'DOG':

``` select AVG(COST / QUANTITY) from PETRESCUE where ANIMAL = 'Dog' ```


## SCALAR and STRING FUNCTIONS

SCALAR: Perform operations on every input value
Examples: ROUND(), LENGTH(), UCASE, LCASE
Example: Round UP or DOWN every calue in COST:

``` select ROUND(COST) from PETRESCUE ```

Example: Retrieve the length of each value in ANIMAL:

``` select LENGTH (ANIMAL) from PETRESCUE ```

## UCASE, LCASE

Example: Retrieve ANIMAL values in UPPERCASE

``` select UCASE(ANIMAL) from PETRESCUE ```

Example: Use the function in WHERE clause:

``` select * from PETRESCUE where LCASE(ANIMAL) = 'cat' ```

Example: Use the DISTINCT function to get unique values:

``` select DISTINCT(UCASE(ANIMAL)) from PETRESCUE ```